// src/components/common/CurrencySelector.vue
<script setup lang="ts">
import { useCurrencyStore, type CurrencyCode } from '@/stores/currency'

const currencyStore = useCurrencyStore()
</script>

<template>
  <select
    :value="currencyStore.currency"
    class="control-select"
    aria-label="Select currency"
    @change="currencyStore.setCurrency(($event.target as HTMLSelectElement).value as CurrencyCode)"
  >
    <option v-for="c in currencyStore.CURRENCIES" :key="c.code" :value="c.code">
      {{ c.code }}
    </option>
  </select>
</template>

// components/common/CurrencySelector.tsx
'use client'

import { useCurrencyStore, type CurrencyCode, CURRENCIES } from '@/lib/stores/currency'

export function CurrencySelector() {
  const { currency, setCurrency } = useCurrencyStore()

  return (
    <select
      value={currency}
      className="control-select"
      aria-label="Select currency"
      onChange={(e) => setCurrency(e.target.value as CurrencyCode)}
    >
      {CURRENCIES.map((c) => (
        <option key={c.code} value={c.code}>
          {c.code}
        </option>
      ))}
    </select>
  )
}
