// src/components/common/ThemeToggle.vue
<script setup lang="ts">
import { SunIcon, MoonIcon } from '@heroicons/vue/24/outline'
import { useThemeStore } from '@/stores/theme'

const theme = useThemeStore()
</script>

<template>
  <button
    type="button"
    class="control-button"
    :aria-label="theme.isDark ? 'Switch to light mode' : 'Switch to dark mode'"
    @click="theme.toggle()"
  >
    <SunIcon v-if="theme.isDark" class="w-4 h-4" />
    <MoonIcon v-else class="w-4 h-4" />
  </button>
</template>

// components/common/ThemeToggle.tsx
'use client'

import { SunIcon, MoonIcon } from '@heroicons/react/24/outline'
import { useThemeStore } from '@/lib/stores/theme'

export function ThemeToggle() {
  const { isDark, toggle } = useThemeStore()

  return (
    <button
      type="button"
      className="control-button"
      aria-label={isDark ? 'Switch to light mode' : 'Switch to dark mode'}
      onClick={toggle}
    >
      {isDark ? <SunIcon className="w-4 h-4" /> : <MoonIcon className="w-4 h-4" />}
    </button>
  )
}
