// components/common/AppearanceControls.tsx
import { CurrencySelector } from './CurrencySelector'
import { ThemeToggle } from './ThemeToggle'

interface AppearanceControlsProps {
  showCurrency?: boolean
  showTheme?: boolean
}

export function AppearanceControls({ showCurrency = true, showTheme = true }: AppearanceControlsProps) {
  return (
    <div className="appearance-controls" role="group" aria-label="Appearance settings">
      {showCurrency && <CurrencySelector />}
      {showTheme && <ThemeToggle />}
    </div>
  )
}

// src/components/common/AppearanceControls.vue
<script setup lang="ts">
import CurrencySelector from '@/components/common/CurrencySelector.vue'
import ThemeToggle from '@/components/common/ThemeToggle.vue'

withDefaults(defineProps<{
  showCurrency?: boolean
  showTheme?: boolean
}>(), {
  showCurrency: true,
  showTheme: true,
})
</script>

<template>
  <div class="appearance-controls" role="group" aria-label="Appearance settings">
    <CurrencySelector v-if="showCurrency" />
    <ThemeToggle v-if="showTheme" />
  </div>
</template>
