// components/common/StatusBadge.tsx
const STATUS_COLORS: Record<string, string> = {
  pending: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',
  processing: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
  shipped: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-400',
  delivered: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
  cancelled: 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400',
  approved: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
  rejected: 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400',
  active: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
  hidden: 'bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-400',
  archived: 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-500',
}

export function StatusBadge({ status }: { status: string }) {
  return (
    <span className={`badge capitalize ${STATUS_COLORS[status] || 'bg-gray-100 text-gray-800'}`}>
      {status}
    </span>
  )
}

// src/components/common/StatusBadge.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{ status: string }>()

const colorClass = computed(() => {
  const map: Record<string, string> = {
    pending: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',
    processing: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
    shipped: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-400',
    delivered: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
    cancelled: 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400',
    approved: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
    rejected: 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400',
    active: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
    hidden: 'bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-400',
    archived: 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-500',
  }
  return map[props.status] || 'bg-gray-100 text-gray-800'
})
</script>

<template>
  <span class="badge capitalize" :class="colorClass">{{ status }}</span>
</template>
